### ISSUE TITLE
Keep order of features in task

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3#524]
We kind of unnecessarily reorder them for an internal optimization.

See https://stackoverflow.com/questions/62646969/mlr3s-taskfeature-names-is-re-ordering-variables-in-r.

**Comment by AlanInglis** [comment]
Can you suggest a work-around for this issue? The suggestion given here  https://stackoverflow.com/questions/62646969/mlr3s-taskfeature-names-is-re-ordering-variables-in-r by jakob-r has no effect as task$data() also reorders the features.

**Comment by mllg** [comment]
Should be fixed by #525. As a workaroud, you can use pass the features explicitly, e.g. by calling `task$data(cols = intersect(task$backend$colnames, task$feature_names))` instead of `task$data()`.

**Comment by AlanInglis** [comment]
Thanks for the feedback. I see you have fixed the issue as of #525. However, I'm not sure what is actually different? task$feature_names, is still reordering the variables? Excuse my stupidity, but is it just the case that the CRAN version isn't the same version as what is on GitHub? I have tried using `remotes::install_github("mlr-org/mlr3")` ... but the features are still getting re-ordered

**Comment by mllg** [comment]
Update: After some discussions we figured out that something like a default order of columns is difficult to define after some preprocessing steps in mlr3pipelines. Thus I reversed this change for now.

If you want your features to be in a specific order, you can still do two things:

1. After task construction, overwrite `task$col_roles$feature` with the feature names in the desired order.
2. If you rely on the order, never call `task$data()` without explicitly providing the columns. I.e., call `task$data(cols = cols_ordered)` instead of just `task$data()`.

**Comment by AlanInglis** [comment]
This is disappointing to hear as my package requires the end user to supply both an mlr3 task and mlr3 trained model as function arguments... and since the model is trained on the task, reordering the columns of task inside of my functions will result in an error as the order no longer matches that of the trained model.

**Comment by mllg** [comment]
> This is disappointing to hear as my package requires the end user to supply both an mlr3 task and mlr3 trained model as function arguments...
> and since the model is trained on the task, reordering the columns of task inside of my functions will result in an error as the order no longer matches that of the trained model.

Can you elaborate what kind of model you fit and why it depends on the order of features? As mentioned above, you can manually set the order by overwriting `task$col_roles$feature`:

```r
task = TaskClassif$new("iris", backend = iris, target = "Species")

# features have been reordered alphabetically:
head(task$data())

# restore originial order of features
task$col_roles$feature = setdiff(names(iris), "Species")

head(task$data())
```

**Comment by berndbischl** [comment]
Can you give some kind of a minimal example that a) shows what you want to achieve and b) what goes wrong?

**Comment by AlanInglis** [comment]
So I have created a visualisation package. And to create the visualisations the user has to supply both a task and model as function arguments. For example, the user would do something like this:

`# Create mlr3 task, learner and model:
task <- TaskRegr$new(id = "myData", backend = myData, target = "y")
lrn = lrn("regr.ranger", importance = "permutation")
model <- lrn$train(task)`

They would then pass the task and the model as function arguments, in my package, to create the visualisations, so something like this:

`# Use the mlr3 task and model in my package function
 newVisualisation <- myFunction(task, model)
plot(newVisualisation)`

But the issue is that inside of my package, I am relying on the order of the variables being the same as the dataset. For example, I'm using the `iml` package to calculate interaction strengths between variables.... and to do this, I was passing the `mlr3` created model to `iml` and then plotting. But because the task has reordered the variables to be different from the dataset, the plots are now incorrectly labelled (and it is a non-trivial task to reorder the plots).
Also, since `iml` requires the trained model and not the task, reordering the task (inside of my package functions)has no effect  as the model has been trained on the 'incorrect' column-order task. 
Also, I was trying to avoid passing the original dataset as a function argument, so I couldn't reorder the task inside my functions anyway... but as stated above, since a lot of stuff in my package relies on the `mlr3` trained model, reordering the task after the model has been trained has no effect. 

The solution you are suggesting, unfortunately, relies on the end-user reordering the columns themselves.

I hope what I said makes sense

**Comment by mllg** [comment]
Here is an example with iml:

```r
library(mlr3)
library(iml) 

data("BostonHousing", package = "mlbench")
task = TaskRegr$new("bh", BostonHousing, target = "medv")
learner = lrn("regr.rpart")
learner$train(task)

X = as.data.frame(task$data(cols = task$feature_names))
y = task$truth()
predictor = Predictor$new(learner$model, data = X, y = y)

effs = FeatureEffects$new(predictor)
plot(effs)
```

You are right, the plot is reordered alphabetically ... The scenarios:

1. The user passes the data as `data.frame()` and you create the task internally. Here the reordering happens during the task construction, but you can easily restore the original order in the task (`task$col_roles$feature = setdiff(names(BostonHousing), "medv")`).

2. The user provides a task. Then the features in the plot are in the same order as the features in the task, so no re-ordering should be necessary. 

AFAICT you are in scenario (2), so the user creates a task and accidentally changes the order of features?

**Comment by mllg** [comment]
I'm not insisting that reordering the features during construction is a good idea. I made the change before to keep the original order which caused some reverse dependencies to break. No big deal, we can fix that. But if we decide to change it, I need to completely understand the problem to ensure that we only have to repair it once.

**Comment by AlanInglis** [comment]
Thanks for taking the time to talk to me... But you are correct that I am in scenario (2)... At the moment, the user creates a task and model externally and provides them as function arguments for my package. The way I had my function constructed was that I was obtaining the data from task$data() internally and assigning the column names to my plots based on task$data(). I was also using the model$importance (which is ordered from high to low values)... I have come up with a solution to internally reorder the variables so they are displaying the correct values... but at the moment, when plotting, the plots are all alphabetical. Which can, at times, be unintuitive to read. For example, the image below will display the variables in alphanumerical order... I guess this isn't the end of the world... but it is not ideal.
<img width="752" alt="Screenshot 2020-07-22 at 20 19 59" src="https://user-images.githubusercontent.com/43614173/88219004-d0c54900-cc58-11ea-98d6-3de2b0908d2e.png">
